### ISSUE TITLE
Probe IDs Not Properly Mapping to Entre Gene IDs

### ISSUE THREAD

**Issue by BGemler** [auerbachs/BMDExpress-2#14]
Hello,

Running into a bug where some Probe IDs are not mapping to an Entrez Gene ID in the BMD analysis tab of BMDExpress2. These unmapped IDs are unable to be used in downstream pathway analysis. 

Example of bug:
Manifest: BioSpyder WT_Mouse
Mapped Probe ID (Entrez Gene ID): Tnfrsf12a_60668 (27279)
Unmapped Probe IDs: Gata1_69677, Plin2_31642, Cyp3a11_30591

I've manually checked the local BioSpyder WT_Mouse probe2gene file - all 3 unmapped Probe IDs are found in the file.

**Comment by auerbachs** [comment]
These must be new probes or the mapping based on sequence by our contractors did not correctly map to the genes based on Refseq, hence they were not included. If you would like to include them in your analysis I suggest you perform a defined category analysis. This is the equivalent of using you own probe to gene mapping and your own pathway annotation. If you would like example files and guidance on how to do this you can contact me at auerbachs@niehs.nih.gov

**Comment by japhill** [comment]
Is it possible that you supply your input file so I can examine it to make sure all is well?  We checked the probe mapping file and the pathway mapping files and think it should be okay.  It would be best to test with an actually input file to see if another situation is occurring.

**Comment by japhill** [comment]
[test.txt](https://github.com/auerbachs/BMDExpress-2/files/6189419/test.txt)
Here is an example file that I created using the probe ids that you mentioned above.  All the probe ids mapped and were present in pathway analysis. A couple things to consider: 1. please make sure that there is no white space on either side of the probe id in file except the tab that is the field delimiter.  2. please check the filtration options before category analysis.  it is possible that these genes are getting filtered out before making it to the pathway result set.  If you are able to paste your file, I can test to be sure.

**Comment by BGemler** [comment]
Hello Scott and Japhill,

Thank you for the rapid response! I've generated a sanitized dataset in an attempt to replicate what's going on - see attached 'bmd2_test.txt', which contains both the above referenced mapped and unmapped probe IDs with log2 counts.

To my surprise, when running BMDExpress2 with the above file, all probe IDs mapped to gene IDs. However, when I split the files into multiple expression data files, one containing the mapped probe ID ('bmd2_test-1.txt') and the other the previously unmapped probe IDs ('bmd2_test-2.txt'), the probe IDs contained in the second data file return to being unmapped. There is no change in the probe ID lines between 'bmd2_test-2.txt' and 'bmd2_test.txt'. 

It looks like there may be an issue that pops up when performing BMD analysis on more than 1 expression data file at once. An immediate solution is to analyze each file individually, but is there a better solution so that I can batch analyze many expression data files? I've attached screenshots of the BMD analysis run and results screen.

Thank you!
-Bryan
[bmd2_test.txt](https://github.com/auerbachs/BMDExpress-2/files/6189754/bmd2_test.txt)
[bmd2_test-1.txt](https://github.com/auerbachs/BMDExpress-2/files/6189755/bmd2_test-1.txt)
[bmd2_test-2.txt](https://github.com/auerbachs/BMDExpress-2/files/6189756/bmd2_test-2.txt)
![bmdexpress2_settings](https://user-images.githubusercontent.com/49172154/112149507-713b8680-8bb5-11eb-903e-8ff1e93affa3.PNG)
![bmdexpress2_results](https://user-images.githubusercontent.com/49172154/112149512-726cb380-8bb5-11eb-8daa-5c3b514d1de4.PNG)

**Comment by japhill** [comment]
Bryan,
You stumbled on an issue that is corrected in the source code, but has not been released yet.  We are planning to release a fix for this in the near future along several other new items. Originally it was assumed that an expression file would would contain all the probes for the platform.  As time has progressed, this is not always the case these days with the new platforms.  Unfortunately (but also fortunately) the best way to load these files currently is one at a time.  We look forward to releasing the next version which will address the bulk load/probe2gene annotation across multiple files.

**Comment by BGemler** [comment]
Got it. I'll run each expression file manually for now, and be on the lookout for a new BMDExpress2 release. 

Thank you very much!
