### ISSUE TITLE
Determination of the BMR level

### ISSUE THREAD

**Issue by johannanyf** [auerbachs/BMDExpress-2#3]
Hi,

I am modelling a set of compounds that were all on the same plate and thus all have exactly the same solvent control data. I chose to model with "non constant variance" and was expecting that for all the chemicals the horizontal BMR line was at the same level. However, this was not the case. It seems that if the compound behaves "weird", this affects the BMR level chosen, although with non-constant variance I thought I only take into account the solvent control values.
Can someone explain to me why this is the case?

Thanks in advance,
Johanna

**Comment by auerbachs** [comment]
Hi Johanna,

Thanks for your question related to the BMR changing across models with non-constant variance. When using non-constant variance assumption the SD BMR is not solely tied to the control SD. It also is dependent on the model estimated background noise (i.e., where the model crosses the y-axis) which will likely be slightly different for each model. Its stated more specifically in the BMDS  help manual... "Std. Dev. (Standard Deviation) means the response associated with the BMR will be the background estimate plus or minus the product of the BMR Factor (BMRF) times the standard deviation for the control group data.”. We have updated the wiki to provide better clarity on this issue. Thanks to Jeff Gift and Allen Davis of the USEPA for help with answering this question.

Scott
