### ISSUE TITLE
Custom GO annotations

### ISSUE THREAD

**Issue by mattjmeier** [auerbachs/BMDExpress-2#4]
Hello,

I'm interested in using BMDExpress2 for organisms that are not currently represented in the 'update annotations' menu.

I see that it is currently possible to import data using 'generic' probe IDs; it's great that you provide this functionality. However, to get the full utility of the software (i.e., functional classifications) it would be ideal if I could import a mapping file that links, for example, an Ensembl gene ID to its associated GO term annotations. I am currently working on environmental test species, so this would be useful to me.

Specifically, I'm using Folsomia candida (http://metazoa.ensembl.org/Folsomia_candida/Info/Index) in an upcoming experiment. In terms of annotations, I have a TxDb object (from R annotation packages... in the form an SQLITE database), a GFF, GTF, and could easily create a flat text file with the required mappings.

I took a quick look through ChipInfo.java, FileAnnotation.java, and ArrayAnnotation.java but I can't quite pin down what would need to be done to point BMDExpress2 to a custom file, though locally I can see that there are various mapping-type files in bmdexpress2/data/annotations/ (e.g., ./arrays/BioSpyder/S1500_Human/genes2gos.gz).

Let me know if you have any suggestions for me, or could shed some light on how the annotations actually get into the software. I am willing to fork the repository and test things out if you could give me any guidance (I'm not a programmer by trade, but I can try my best). As an idea for future development, it would be great to have the ability to add a button to the 'update annotations' window that would enable a user to provide a custom mapping file.

Thanks!!

**Comment by mattjmeier** [comment]
I see now after some more reading that you offer Defined Category Analysis as well.

I will try this out!

Thanks,
Matt

**Comment by auerbachs** [comment]
Excellent. I was just sitting down to explain how to use the Defined Category Analysis. 

To carry out a Defined Category Analysis you will need a probe map file (probes to gene map, Example: https://github.com/auerbachs/BMDExpress-2/blob/master/Category%20Map%20File_%20MsigDB%20Hallmark%20Gene%20Sets.txt)
and a Category map file (genes to pathways/gene sets, Example: https://github.com/auerbachs/BMDExpress-2/blob/master/Category%20Map%20File_%20MsigDB%20Hallmark%20Gene%20Sets.txt)

The following video (start at 5:50 for Defined Category Analysis) explains the rest: https://www.youtube.com/watch?v=bsBQftLUWZs&t=379s&list=PLX2Rd5DjtiTeR84Z4wRSUmKYMoAbilZEc&index=14

Good luck!
